name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USER }}
          script: |
            cd burgerbot
            git pull
            cd ../bots/burgerbot
            ps aux | grep burgerbot | grep -v grep | awk '{print $2}' | xargs -r kill -9
            cp ~/burgerbot/burgerbot.py burgerbot.py
            source .env
            nohup /root/.poetry/bin/poetry run python burgerbot.py > log.txt &
            echo 'done'
